apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: traffic-split
  namespace: linkerd-project
spec:
  service: api-service
  backends:
  - service: kafka-client
    weight: 300m
  - service: redis-client
    weight: 300m
  - service: grpc-client
    weight: 300m
  - service: error-injector
    weight: 100m