apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: container-kill
  namespace: chaos-testing
spec:
  action: container-kill
  mode: one
  containerName: 'kafka-publisher'
  selector:
    namespaces:
      - linkerd-project
    labelSelectors:
      "app": "kafka-client" #"redis-client" # ""
  scheduler:
    cron: '@every 30s'