apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  value: ''
  selector:
    namespaces:
      - linkerd-project
    labelSelectors:
      "app": "kafka-client" #"redis-client" # ""
  duration: '30s'
  scheduler:
    cron: '@every 2m'