apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - linkerd-project
    labelSelectors:
      "app": "kafka-client" #"redis-client" # ""
  scheduler:
    cron: '@every 2m'